#!/usr/bin/env bash

# frontend/setup.sh
# Setup script for Watch!fy frontend
# Usage: ./setup.sh [--reset] [--skip-install]

set -euo pipefail
IFS=$'\n\t'

# ─── Constants ────────────────────────────────────────────────────────────────

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly ENV_FILE="$SCRIPT_DIR/.env"
readonly ENV_EXAMPLE_FILE="$SCRIPT_DIR/.env.example"
readonly REQUIRED_NODE_VERSION=18
readonly BACKEND_URL="http://localhost:8000"
readonly APP_NAME="Watch\!fy"

# ─── Colours ──────────────────────────────────────────────────────────────────

if [[ -t 1 ]]; then
  RED="\033[0;31m"; GREEN="\033[0;32m"; YELLOW="\033[1;33m"
  BLUE="\033[0;34m"; CYAN="\033[0;36m"; BOLD="\033[1m"; RESET="\033[0m"
else
  RED="" GREEN="" YELLOW="" BLUE="" CYAN="" BOLD="" RESET=""
fi

# ─── Logging ──────────────────────────────────────────────────────────────────

info()    { echo -e "${BLUE}ℹ${RESET}  $*"; }
success() { echo -e "${GREEN}✔${RESET}  $*"; }
warn()    { echo -e "${YELLOW}⚠${RESET}  $*"; }
error()   { echo -e "${RED}✘${RESET}  $*" >&2; }
step()    { echo -e "\n${BOLD}${CYAN}▶ $*${RESET}"; }
die()     { error "$*"; exit 1; }

# ─── Flags ────────────────────────────────────────────────────────────────────

RESET_ENV=false
SKIP_INSTALL=false

for arg in "$@"; do
  case $arg in
    --reset)         RESET_ENV=true ;;
    --skip-install)  SKIP_INSTALL=true ;;
    --help|-h)
      echo "Usage: $(basename "$0") [--reset] [--skip-install]"
      echo ""
      echo "  --reset          Overwrite existing .env with defaults"
      echo "  --skip-install   Skip npm/yarn dependency installation"
      exit 0
      ;;
    *) die "Unknown argument: $arg. Run with --help for usage." ;;
  esac
done

# ─── Helpers ──────────────────────────────────────────────────────────────────

command_exists() { command -v "$1" &>/dev/null; }

detect_package_manager() {
  if [[ -f "$SCRIPT_DIR/pnpm-lock.yaml" ]]; then echo "pnpm"
  elif [[ -f "$SCRIPT_DIR/yarn.lock" ]];     then echo "yarn"
  elif [[ -f "$SCRIPT_DIR/package-lock.json" ]]; then echo "npm"
  else echo "npm"
  fi
}

node_version() { node -e "process.stdout.write(process.versions.node.split('.')[0])"; }

check_env_vars() {
  local missing=()
  while IFS= read -r line; do
    [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
    local key="${line%%=*}"
    [[ -z "${!key:-}" ]] && missing+=("$key")
  done < "$ENV_EXAMPLE_FILE"

  if [[ ${#missing[@]} -gt 0 ]]; then
    warn "The following .env variables are unset or empty:"
    for var in "${missing[@]}"; do
      echo "     ${YELLOW}•${RESET} $var"
    done
  fi
}

# ─── Main ─────────────────────────────────────────────────────────────────────

main() {
  echo -e "${BOLD}"
  echo "  ╔══════════════════════════════════╗"
  echo "  ║   ${APP_NAME} — Frontend Setup       ║"
  echo "  ╚══════════════════════════════════╝"
  echo -e "${RESET}"

  # 1. Verify prerequisites
  step "Checking prerequisites"

  command_exists node || die "Node.js is not installed. Install it from https://nodejs.org"
  local node_ver
  node_ver="$(node_version)"
  if (( node_ver < REQUIRED_NODE_VERSION )); then
    die "Node.js v${REQUIRED_NODE_VERSION}+ required (found v${node_ver}). Update at https://nodejs.org"
  fi
  success "Node.js v$(node --version | tr -d v)"

  local pm
  pm="$(detect_package_manager)"
  command_exists "$pm" || die "'$pm' is not installed."
  success "Package manager: $pm $(${pm} --version)"

  # 2. Install dependencies
  if [[ "$SKIP_INSTALL" == false ]]; then
    step "Installing dependencies"
    "$pm" install && success "Dependencies installed"
  else
    warn "Skipping dependency installation (--skip-install)"
  fi

  # 3. Environment file
  step "Configuring environment"

  if [[ "$RESET_ENV" == true && -f "$ENV_FILE" ]]; then
    warn "Removing existing .env (--reset)"
    rm "$ENV_FILE"
  fi

  if [[ ! -f "$ENV_FILE" ]]; then
    info "Creating .env from defaults..."

    # Prefer .env.example as source of truth if it exists
    if [[ -f "$ENV_EXAMPLE_FILE" ]]; then
      cp "$ENV_EXAMPLE_FILE" "$ENV_FILE"
      success "Copied .env from .env.example"
    else
      cat > "$ENV_FILE" << EOF
# Watch!fy — Frontend Environment
# Generated by setup.sh on $(date +"%Y-%m-%d %H:%M:%S")

# TMDB API — get your key at https://www.themoviedb.org/settings/api
VITE_TMDB_API_KEY=

# Backend API base URL
VITE_API_URL=${BACKEND_URL}

# Optional: override the app's base path (default: /)
VITE_BASE_URL=/

# Optional: dev server port (default: 3000)
VITE_PORT=3000
EOF
      success "Created .env with default values"
    fi
    warn "Update ${BOLD}.env${RESET}${YELLOW} with your TMDB API key before starting the dev server."
  else
    success "Using existing .env"
  fi

  # 4. Validate env vars against .env.example
  if [[ -f "$ENV_EXAMPLE_FILE" ]]; then
    check_env_vars
  fi

  # 5. Check backend reachability (non-fatal)
  step "Checking backend connectivity"
  if command_exists curl; then
    if curl -sf --max-time 3 "${BACKEND_URL}/health" &>/dev/null; then
      success "Backend is reachable at ${BACKEND_URL}"
    else
      warn "Backend not reachable at ${BACKEND_URL} — start it before running the app."
    fi
  else
    info "curl not found, skipping backend check."
  fi

  # 6. Done
  echo ""
  echo -e "${GREEN}${BOLD}  Setup complete!${RESET}"
  echo ""
  echo -e "  ${BOLD}Next steps:${RESET}"
  echo -e "  ${CYAN}1.${RESET} Update ${BOLD}.env${RESET} with your TMDB API key"
  echo -e "  ${CYAN}2.${RESET} Start the dev server:   ${BOLD}${pm} run dev${RESET}"
  echo -e "  ${CYAN}3.${RESET} Start the backend:      ${BOLD}cd ../backend && ./setup.sh${RESET}"
  echo ""
}

main "$@"