/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchlistIndexRouteImport } from './routes/watchlist/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as NotFoundIndexRouteImport } from './routes/not-found/index'
import { Route as LikedIndexRouteImport } from './routes/liked/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as DiscoverIndexRouteImport } from './routes/discover/index'
import { Route as WatchTypeSlugRouteImport } from './routes/watch/$type/$slug'
import { Route as DetailsTypeSlugRouteImport } from './routes/details/$type/$slug'
import { Route as WatchTypeSlugSeasonEpisodeRouteImport } from './routes/watch/$type/$slug/$season/$episode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistIndexRoute = WatchlistIndexRouteImport.update({
  id: '/watchlist/',
  path: '/watchlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundIndexRoute = NotFoundIndexRouteImport.update({
  id: '/not-found/',
  path: '/not-found/',
  getParentRoute: () => rootRouteImport,
} as any)
const LikedIndexRoute = LikedIndexRouteImport.update({
  id: '/liked/',
  path: '/liked/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchTypeSlugRoute = WatchTypeSlugRouteImport.update({
  id: '/watch/$type/$slug',
  path: '/watch/$type/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsTypeSlugRoute = DetailsTypeSlugRouteImport.update({
  id: '/details/$type/$slug',
  path: '/details/$type/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchTypeSlugSeasonEpisodeRoute =
  WatchTypeSlugSeasonEpisodeRouteImport.update({
    id: '/$season/$episode',
    path: '/$season/$episode',
    getParentRoute: () => WatchTypeSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/home/': typeof HomeIndexRoute
  '/liked/': typeof LikedIndexRoute
  '/not-found/': typeof NotFoundIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/search/': typeof SearchIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/watchlist/': typeof WatchlistIndexRoute
  '/details/$type/$slug': typeof DetailsTypeSlugRoute
  '/watch/$type/$slug': typeof WatchTypeSlugRouteWithChildren
  '/watch/$type/$slug/$season/$episode': typeof WatchTypeSlugSeasonEpisodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverIndexRoute
  '/home': typeof HomeIndexRoute
  '/liked': typeof LikedIndexRoute
  '/not-found': typeof NotFoundIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/search': typeof SearchIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/watchlist': typeof WatchlistIndexRoute
  '/details/$type/$slug': typeof DetailsTypeSlugRoute
  '/watch/$type/$slug': typeof WatchTypeSlugRouteWithChildren
  '/watch/$type/$slug/$season/$episode': typeof WatchTypeSlugSeasonEpisodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/home/': typeof HomeIndexRoute
  '/liked/': typeof LikedIndexRoute
  '/not-found/': typeof NotFoundIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/search/': typeof SearchIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/watchlist/': typeof WatchlistIndexRoute
  '/details/$type/$slug': typeof DetailsTypeSlugRoute
  '/watch/$type/$slug': typeof WatchTypeSlugRouteWithChildren
  '/watch/$type/$slug/$season/$episode': typeof WatchTypeSlugSeasonEpisodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover/'
    | '/home/'
    | '/liked/'
    | '/not-found/'
    | '/profile/'
    | '/search/'
    | '/settings/'
    | '/watchlist/'
    | '/details/$type/$slug'
    | '/watch/$type/$slug'
    | '/watch/$type/$slug/$season/$episode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/home'
    | '/liked'
    | '/not-found'
    | '/profile'
    | '/search'
    | '/settings'
    | '/watchlist'
    | '/details/$type/$slug'
    | '/watch/$type/$slug'
    | '/watch/$type/$slug/$season/$episode'
  id:
    | '__root__'
    | '/'
    | '/discover/'
    | '/home/'
    | '/liked/'
    | '/not-found/'
    | '/profile/'
    | '/search/'
    | '/settings/'
    | '/watchlist/'
    | '/details/$type/$slug'
    | '/watch/$type/$slug'
    | '/watch/$type/$slug/$season/$episode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverIndexRoute: typeof DiscoverIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  LikedIndexRoute: typeof LikedIndexRoute
  NotFoundIndexRoute: typeof NotFoundIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  WatchlistIndexRoute: typeof WatchlistIndexRoute
  DetailsTypeSlugRoute: typeof DetailsTypeSlugRoute
  WatchTypeSlugRoute: typeof WatchTypeSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist/': {
      id: '/watchlist/'
      path: '/watchlist'
      fullPath: '/watchlist/'
      preLoaderRoute: typeof WatchlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found/': {
      id: '/not-found/'
      path: '/not-found'
      fullPath: '/not-found/'
      preLoaderRoute: typeof NotFoundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liked/': {
      id: '/liked/'
      path: '/liked'
      fullPath: '/liked/'
      preLoaderRoute: typeof LikedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/': {
      id: '/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$type/$slug': {
      id: '/watch/$type/$slug'
      path: '/watch/$type/$slug'
      fullPath: '/watch/$type/$slug'
      preLoaderRoute: typeof WatchTypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details/$type/$slug': {
      id: '/details/$type/$slug'
      path: '/details/$type/$slug'
      fullPath: '/details/$type/$slug'
      preLoaderRoute: typeof DetailsTypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$type/$slug/$season/$episode': {
      id: '/watch/$type/$slug/$season/$episode'
      path: '/$season/$episode'
      fullPath: '/watch/$type/$slug/$season/$episode'
      preLoaderRoute: typeof WatchTypeSlugSeasonEpisodeRouteImport
      parentRoute: typeof WatchTypeSlugRoute
    }
  }
}

interface WatchTypeSlugRouteChildren {
  WatchTypeSlugSeasonEpisodeRoute: typeof WatchTypeSlugSeasonEpisodeRoute
}

const WatchTypeSlugRouteChildren: WatchTypeSlugRouteChildren = {
  WatchTypeSlugSeasonEpisodeRoute: WatchTypeSlugSeasonEpisodeRoute,
}

const WatchTypeSlugRouteWithChildren = WatchTypeSlugRoute._addFileChildren(
  WatchTypeSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverIndexRoute: DiscoverIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  LikedIndexRoute: LikedIndexRoute,
  NotFoundIndexRoute: NotFoundIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  WatchlistIndexRoute: WatchlistIndexRoute,
  DetailsTypeSlugRoute: DetailsTypeSlugRoute,
  WatchTypeSlugRoute: WatchTypeSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
